export const DEFAULT_CASH = 3000;
export const AUTH_OPTION = 'auth_option';
export const DEFAULT_SCHEMA = 'pos';
export const TENANT_SCHEMA = 'tenant_';
export const TENANT_EX = `${TENANT_SCHEMA}ex`;
export const APP_NAME = process.env.APP_NAME || 'Haibai POS';

export const ENV = {
  prod: 'prod',
  dev: 'dev',
  stage: 'stage',
};

export const POSPermission = {
  ACCEPT_PAYMENT: 'ACCEPT_PAYMENT',
  APPLY_DISCOUNT_WITH_RESTRICTED_ACCESS: 'APPLY_DISCOUNT_WITH_RESTRICTED_ACCESS',
  CHANGE_TAX: 'CHANGE_TAX',
  MANAGE_ALL_OPEN_TICKET: 'MANAGE_ALL_OPEN_TICKET',
  VOID_SAVED_ITEMS: 'VOID_SAVED_ITEMS',
  OPEN_CASH_DRAWER_WITHOUT_MAKING_SALE: 'OPEN_CASH_DRAWER_WITHOUT_MAKING_SALE',
  VIEW_ALL_RECEIPTS: 'VIEW_ALL_RECEIPTS',
  PERFORM_REFUNDS: 'PERFORM_REFUNDS',
  REPRINT_AND_RESEND_RECEIPTS: 'REPRINT_AND_RESEND_RECEIPTS',
  VIEW_SHIFT_REPORT: 'VIEW_SHIFT_REPORT',
  MANAGE_ITEMS: 'MANAGE_ITEMS',
  VIEW_COST_OF_ITEMS: 'VIEW_COST_OF_ITEMS',
  CHANGE_SETTINGS: 'CHANGE_SETTINGS',
  ACCESS_TO_LIVE_CHAT: 'ACCESS_TO_LIVE_CHAT',
} as const;

export const BackOfficePermission = {
  VIEW_SALE_REPORT: 'VIEW_SALE_REPORT',
  CANCEL_RECEIPTS: 'CANCEL_RECEIPTS',
  MANAGE_ITEMS: 'MANAGE_ITEMS',
  VIEW_COST_OF_ITEMS: 'VIEW_COST_OF_ITEMS',
  MANAGE_EMPLOYEES: 'MANAGE_EMPLOYEES',
  MANAGE_CUSTOMERS: 'MANAGE_CUSTOMERS',
  EDIT_GENERAL_SETTINGS: 'EDIT_GENERAL_SETTINGS',
  MANAGE_BILLING: 'MANAGE_BILLING',
  MANAGE_PAYMENT_TYPE: 'MANAGE_PAYMENT_TYPE',
  MANAGE_LOYALTY_PROGRAM: 'MANAGE_LOYALTY_PROGRAM',
  MANAGE_TAXES: 'MANAGE_TAXES',
  MANAGE_KITCHEN_PRINTER: 'MANAGE_KITCHEN_PRINTER',
  MANAGE_DINING_OPTIONS: 'MANAGE_DINING_OPTIONS',
  MANAGE_POS_DEVICE: 'MANAGE_POS_DEVICE',
  ACCESS_TO_LIVE_CHAT: 'ACCESS_TO_LIVE_CHAT',
} as const;

export type BackOfficePermissionType = (typeof BackOfficePermission)[keyof typeof BackOfficePermission];
export type POSPermissionType = (typeof POSPermission)[keyof typeof POSPermission];

export type TenantPermissionType = BackOfficePermissionType | POSPermissionType;
